<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-3ICCF01F" failures="1" tests="2" name="com.khcproject.qa.testcases.MakeAppointmentTest" time="13.020" errors="0" timestamp="2023-08-15T16:44:15 IST" skipped="1">
  <testcase classname="com.khcproject.qa.testcases.MakeAppointmentTest" name="makeAppointment" time="13.020">
    <failure message="Validations are successful
	expected [Appointment booked for email_Tue_Aug_15_16_44_14_IST_2023@gmail.com] but found [Appointment booked for email_Tue_Aug_15_16_44_12_IST_2023@gmail.com]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Validations are successful
expected [Appointment booked for email_Tue_Aug_15_16_44_14_IST_2023@gmail.com] but found [Appointment booked for email_Tue_Aug_15_16_44_12_IST_2023@gmail.com]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at com.khcproject.qa.testcases.MakeAppointmentTest.makeAppointment(MakeAppointmentTest.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- makeAppointment -->
  <system-out/>
  <testcase classname="com.khcproject.qa.testcases.MakeAppointmentTest" name="makeAppointmentUsingDataDriven">
    <skipped/>
  </testcase> <!-- makeAppointmentUsingDataDriven -->
  <system-out/>
</testsuite> <!-- com.khcproject.qa.testcases.MakeAppointmentTest -->
